export {};
const express = require('express')
const router = express.Router()

router.get('/api/', (req, res) => {
    const a_json = {
"list-adm-edif-pub-militar-a": "http://localhost:3000/api/list-adm-edif-pub-militar-a"
,"list-adm-edif-pub-militar-p": "http://localhost:3000/api/list-adm-edif-pub-militar-p"
,"list-adm-posto-fiscal-p": "http://localhost:3000/api/list-adm-posto-fiscal-p"
,"list-eco-edif-agropec-ext-vegetal-pesca-p": "http://localhost:3000/api/list-eco-edif-agropec-ext-vegetal-pesca-p"
,"list-eco-ext-mineral-a": "http://localhost:3000/api/list-eco-ext-mineral-a"
,"list-eco-ext-mineral-p": "http://localhost:3000/api/list-eco-ext-mineral-p"
,"list-enc-est-gerad-energia-eletrica-p": "http://localhost:3000/api/list-enc-est-gerad-energia-eletrica-p"
,"list-enc-hidreletrica-p": "http://localhost:3000/api/list-enc-hidreletrica-p"
,"list-enc-termeletrica-p": "http://localhost:3000/api/list-enc-termeletrica-p"
,"list-hid-banco-areia-a": "http://localhost:3000/api/list-hid-banco-areia-a"
,"list-hid-barragem-l": "http://localhost:3000/api/list-hid-barragem-l"
,"list-hid-barragem-p": "http://localhost:3000/api/list-hid-barragem-p"
,"list-hid-corredeira-l": "http://localhost:3000/api/list-hid-corredeira-l"
,"list-hid-corredeira-p": "http://localhost:3000/api/list-hid-corredeira-p"
,"list-hid-ilha-a": "http://localhost:3000/api/list-hid-ilha-a"
,"list-hid-massa-dagua-a": "http://localhost:3000/api/list-hid-massa-dagua-a"
,"list-hid-queda-dagua-l": "http://localhost:3000/api/list-hid-queda-dagua-l"
,"list-hid-recife-a": "http://localhost:3000/api/list-hid-recife-a"
,"list-hid-rocha-em-agua-a": "http://localhost:3000/api/list-hid-rocha-em-agua-a"
,"list-hid-sumidouro-vertedouro-p": "http://localhost:3000/api/list-hid-sumidouro-vertedouro-p"
,"list-hid-terreno-sujeito-inundacao-a": "http://localhost:3000/api/list-hid-terreno-sujeito-inundacao-a"
,"list-hid-trecho-drenagem-l": "http://localhost:3000/api/list-hid-trecho-drenagem-l"
,"list-hid-trecho-massa-dagua-a": "http://localhost:3000/api/list-hid-trecho-massa-dagua-a"
,"list-lim-municipio-a": "http://localhost:3000/api/list-lim-municipio-a"
,"list-lim-outros-limites-oficiais-l": "http://localhost:3000/api/list-lim-outros-limites-oficiais-l"
,"list-lim-pais-a": "http://localhost:3000/api/list-lim-pais-a"
,"list-lim-terra-indigena-a": "http://localhost:3000/api/list-lim-terra-indigena-a"
,"list-lim-terra-indigena-p": "http://localhost:3000/api/list-lim-terra-indigena-p"
,"list-lim-unidade-conservacao-nao-snuc-a": "http://localhost:3000/api/list-lim-unidade-conservacao-nao-snuc-a"
,"list-lim-unidade-federacao-a": "http://localhost:3000/api/list-lim-unidade-federacao-a"
,"list-lim-unidade-protecao-integral-a": "http://localhost:3000/api/list-lim-unidade-protecao-integral-a"
,"list-lim-unidade-uso-sustentavel-a": "http://localhost:3000/api/list-lim-unidade-uso-sustentavel-a"
,"list-loc-aglomerado-rural-isolado-p": "http://localhost:3000/api/list-loc-aglomerado-rural-isolado-p"
,"list-loc-aldeia-indigena-p": "http://localhost:3000/api/list-loc-aldeia-indigena-p"
,"list-loc-area-edificada-a": "http://localhost:3000/api/list-loc-area-edificada-a"
,"list-loc-capital-p": "http://localhost:3000/api/list-loc-capital-p"
,"list-loc-cidade-p": "http://localhost:3000/api/list-loc-cidade-p"
,"list-loc-vila-p": "http://localhost:3000/api/list-loc-vila-p"
,"list-rel-curva-batimetrica-l": "http://localhost:3000/api/list-rel-curva-batimetrica-l"
,"list-rel-curva-nivel-l": "http://localhost:3000/api/list-rel-curva-nivel-l"
,"list-rel-duna-a": "http://localhost:3000/api/list-rel-duna-a"
,"list-rel-elemento-fisiografico-natural-l": "http://localhost:3000/api/list-rel-elemento-fisiografico-natural-l"
,"list-rel-elemento-fisiografico-natural-p": "http://localhost:3000/api/list-rel-elemento-fisiografico-natural-p"
,"list-rel-pico-p": "http://localhost:3000/api/list-rel-pico-p"
,"list-rel-ponto-cotado-altimetrico-p": "http://localhost:3000/api/list-rel-ponto-cotado-altimetrico-p"
,"list-rel-ponto-cotado-batimetrico-p": "http://localhost:3000/api/list-rel-ponto-cotado-batimetrico-p"
,"list-tra-eclusa-l": "http://localhost:3000/api/list-tra-eclusa-l"
,"list-tra-edif-const-aeroportuaria-p": "http://localhost:3000/api/list-tra-edif-const-aeroportuaria-p"
,"list-tra-edif-const-portuaria-p": "http://localhost:3000/api/list-tra-edif-const-portuaria-p"
,"list-tra-edif-metro-ferroviaria-p": "http://localhost:3000/api/list-tra-edif-metro-ferroviaria-p"
,"list-tra-pista-ponto-pouso-p": "http://localhost:3000/api/list-tra-pista-ponto-pouso-p"
,"list-tra-ponte-l": "http://localhost:3000/api/list-tra-ponte-l"
,"list-tra-sinalizacao-p": "http://localhost:3000/api/list-tra-sinalizacao-p"
,"list-tra-travessia-l": "http://localhost:3000/api/list-tra-travessia-l"
,"list-tra-travessia-p": "http://localhost:3000/api/list-tra-travessia-p"
,"list-tra-trecho-duto-l": "http://localhost:3000/api/list-tra-trecho-duto-l"
,"list-tra-trecho-ferroviario-l": "http://localhost:3000/api/list-tra-trecho-ferroviario-l"
,"list-tra-trecho-hidroviario-l": "http://localhost:3000/api/list-tra-trecho-hidroviario-l"
,"list-tra-trecho-rodoviario-l": "http://localhost:3000/api/list-tra-trecho-rodoviario-l"
,"list-tra-tunel-l": "http://localhost:3000/api/list-tra-tunel-l"
,"list-veg-brejo-pantano-a": "http://localhost:3000/api/list-veg-brejo-pantano-a"
,"list-veg-mangue-a": "http://localhost:3000/api/list-veg-mangue-a"
,"list-veg-veg-restinga-a": "http://localhost:3000/api/list-veg-veg-restinga-a"
}

    res.json(a_json)
})
module.exports=router