const router_entry_point = require('./entry_point')
const router_AdmEdifPubMilitarA = require('./AdmEdifPubMilitarA')
const router_AdmEdifPubMilitarP = require('./AdmEdifPubMilitarP')
const router_AdmPostoFiscalP = require('./AdmPostoFiscalP')
const router_EcoEdifAgropecExtVegetalPescaP = require('./EcoEdifAgropecExtVegetalPescaP')
const router_EcoExtMineralA = require('./EcoExtMineralA')
const router_EcoExtMineralP = require('./EcoExtMineralP')
const router_EncEstGeradEnergiaEletricaP = require('./EncEstGeradEnergiaEletricaP')
const router_EncHidreletricaP = require('./EncHidreletricaP')
const router_EncTermeletricaP = require('./EncTermeletricaP')
const router_HidBancoAreiaA = require('./HidBancoAreiaA')
const router_HidBarragemL = require('./HidBarragemL')
const router_HidBarragemP = require('./HidBarragemP')
const router_HidCorredeiraL = require('./HidCorredeiraL')
const router_HidCorredeiraP = require('./HidCorredeiraP')
const router_HidIlhaA = require('./HidIlhaA')
const router_HidMassaDaguaA = require('./HidMassaDaguaA')
const router_HidQuedaDaguaL = require('./HidQuedaDaguaL')
const router_HidRecifeA = require('./HidRecifeA')
const router_HidRochaEmAguaA = require('./HidRochaEmAguaA')
const router_HidSumidouroVertedouroP = require('./HidSumidouroVertedouroP')
const router_HidTerrenoSujeitoInundacaoA = require('./HidTerrenoSujeitoInundacaoA')
const router_HidTrechoDrenagemL = require('./HidTrechoDrenagemL')
const router_HidTrechoMassaDaguaA = require('./HidTrechoMassaDaguaA')
const router_LimMunicipioA = require('./LimMunicipioA')
const router_LimOutrosLimitesOficiaisL = require('./LimOutrosLimitesOficiaisL')
const router_LimPaisA = require('./LimPaisA')
const router_LimTerraIndigenaA = require('./LimTerraIndigenaA')
const router_LimTerraIndigenaP = require('./LimTerraIndigenaP')
const router_LimUnidadeConservacaoNaoSnucA = require('./LimUnidadeConservacaoNaoSnucA')
const router_LimUnidadeFederacaoA = require('./LimUnidadeFederacaoA')
const router_LimUnidadeProtecaoIntegralA = require('./LimUnidadeProtecaoIntegralA')
const router_LimUnidadeUsoSustentavelA = require('./LimUnidadeUsoSustentavelA')
const router_LocAglomeradoRuralIsoladoP = require('./LocAglomeradoRuralIsoladoP')
const router_LocAldeiaIndigenaP = require('./LocAldeiaIndigenaP')
const router_LocAreaEdificadaA = require('./LocAreaEdificadaA')
const router_LocCapitalP = require('./LocCapitalP')
const router_LocCidadeP = require('./LocCidadeP')
const router_LocVilaP = require('./LocVilaP')
const router_RelCurvaBatimetricaL = require('./RelCurvaBatimetricaL')
const router_RelCurvaNivelL = require('./RelCurvaNivelL')
const router_RelDunaA = require('./RelDunaA')
const router_RelElementoFisiograficoNaturalL = require('./RelElementoFisiograficoNaturalL')
const router_RelElementoFisiograficoNaturalP = require('./RelElementoFisiograficoNaturalP')
const router_RelPicoP = require('./RelPicoP')
const router_RelPontoCotadoAltimetricoP = require('./RelPontoCotadoAltimetricoP')
const router_RelPontoCotadoBatimetricoP = require('./RelPontoCotadoBatimetricoP')
const router_TraEclusaL = require('./TraEclusaL')
const router_TraEdifConstAeroportuariaP = require('./TraEdifConstAeroportuariaP')
const router_TraEdifConstPortuariaP = require('./TraEdifConstPortuariaP')
const router_TraEdifMetroFerroviariaP = require('./TraEdifMetroFerroviariaP')
const router_TraPistaPontoPousoP = require('./TraPistaPontoPousoP')
const router_TraPonteL = require('./TraPonteL')
const router_TraSinalizacaoP = require('./TraSinalizacaoP')
const router_TraTravessiaL = require('./TraTravessiaL')
const router_TraTravessiaP = require('./TraTravessiaP')
const router_TraTrechoDutoL = require('./TraTrechoDutoL')
const router_TraTrechoFerroviarioL = require('./TraTrechoFerroviarioL')
const router_TraTrechoHidroviarioL = require('./TraTrechoHidroviarioL')
const router_TraTrechoRodoviarioL = require('./TraTrechoRodoviarioL')
const router_TraTunelL = require('./TraTunelL')
const router_VegBrejoPantanoA = require('./VegBrejoPantanoA')
const router_VegMangueA = require('./VegMangueA')
const router_VegVegRestingaA = require('./VegVegRestingaA')

async function importAllRouters(app) {
 app.use(router_entry_point)
 app.use(router_AdmEdifPubMilitarA)
 app.use(router_AdmEdifPubMilitarP)
 app.use(router_AdmPostoFiscalP)
 app.use(router_EcoEdifAgropecExtVegetalPescaP)
 app.use(router_EcoExtMineralA)
 app.use(router_EcoExtMineralP)
 app.use(router_EncEstGeradEnergiaEletricaP)
 app.use(router_EncHidreletricaP)
 app.use(router_EncTermeletricaP)
 app.use(router_HidBancoAreiaA)
 app.use(router_HidBarragemL)
 app.use(router_HidBarragemP)
 app.use(router_HidCorredeiraL)
 app.use(router_HidCorredeiraP)
 app.use(router_HidIlhaA)
 app.use(router_HidMassaDaguaA)
 app.use(router_HidQuedaDaguaL)
 app.use(router_HidRecifeA)
 app.use(router_HidRochaEmAguaA)
 app.use(router_HidSumidouroVertedouroP)
 app.use(router_HidTerrenoSujeitoInundacaoA)
 app.use(router_HidTrechoDrenagemL)
 app.use(router_HidTrechoMassaDaguaA)
 app.use(router_LimMunicipioA)
 app.use(router_LimOutrosLimitesOficiaisL)
 app.use(router_LimPaisA)
 app.use(router_LimTerraIndigenaA)
 app.use(router_LimTerraIndigenaP)
 app.use(router_LimUnidadeConservacaoNaoSnucA)
 app.use(router_LimUnidadeFederacaoA)
 app.use(router_LimUnidadeProtecaoIntegralA)
 app.use(router_LimUnidadeUsoSustentavelA)
 app.use(router_LocAglomeradoRuralIsoladoP)
 app.use(router_LocAldeiaIndigenaP)
 app.use(router_LocAreaEdificadaA)
 app.use(router_LocCapitalP)
 app.use(router_LocCidadeP)
 app.use(router_LocVilaP)
 app.use(router_RelCurvaBatimetricaL)
 app.use(router_RelCurvaNivelL)
 app.use(router_RelDunaA)
 app.use(router_RelElementoFisiograficoNaturalL)
 app.use(router_RelElementoFisiograficoNaturalP)
 app.use(router_RelPicoP)
 app.use(router_RelPontoCotadoAltimetricoP)
 app.use(router_RelPontoCotadoBatimetricoP)
 app.use(router_TraEclusaL)
 app.use(router_TraEdifConstAeroportuariaP)
 app.use(router_TraEdifConstPortuariaP)
 app.use(router_TraEdifMetroFerroviariaP)
 app.use(router_TraPistaPontoPousoP)
 app.use(router_TraPonteL)
 app.use(router_TraSinalizacaoP)
 app.use(router_TraTravessiaL)
 app.use(router_TraTravessiaP)
 app.use(router_TraTrechoDutoL)
 app.use(router_TraTrechoFerroviarioL)
 app.use(router_TraTrechoHidroviarioL)
 app.use(router_TraTrechoRodoviarioL)
 app.use(router_TraTunelL)
 app.use(router_VegBrejoPantanoA)
 app.use(router_VegMangueA)
 app.use(router_VegVegRestingaA)
}
module.exports={importAllRouters}
